#!/bin/bash

git branch -D wpengine

set -e

################################################################
## Based on https://github.com/joshleecreates/wpengine-deploy-script
################################################################

# Configure git

git config --global user.email "gitlab-ci@utulsa.co"
git config --global user.name "GitLab CI"

# Generate SSH keys

echo "Setting up private/public key pair..."

mkdir -p ~/.ssh/
echo "$WPE_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
echo "$WPE_SSH_PUBLIC_KEY" > ~/.ssh/id_rsa.pub

# Push to WPEngine

echo "Preparing for WPEngine deploy..."

git checkout --orphan wpengine

# Recursively add .wpe-gitignore files into the .gitignore in that directory
for i in $(find . -type f -name ".wpe-gitignore"); do
    echo -e "\n\n## WP ENGINE GITIGNORE" >> $(dirname $i)/.gitignore;
    cat $i >> $(dirname $i)/.gitignore;
    echo "" >> $(dirname $i)/.gitignore;
done

git rm -rf --cached . > /dev/null

git add -A

git commit -am "WPEngine build at `date`."

if git remote | grep wpe-deploy > /dev/null; then
    git remote rm wpe-deploy
fi

git remote add wpe-deploy $WPE_GIT_REPO

echo "Pushing to WPEngine..."

git push wpe-deploy wpengine:master --force

echo "Successfully deployed."
